### ISSUE TITLE
Clean out / simplify code

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/NeuralTracking#26]
A lot of this codebase is getting difficult to maintain because of legacy features / experiments that yielded worse results than the currently established variant.

Biggest items on the docket:
- [x] Dual quaternion computations (in many newer functions, support for these is even missing). We can always go back to doing things via dual quaternions if we find that matrices are just not stable-enough -- #27 
 - [x] Recursive variant of the KDTree code. That's just causing extra compiler warnings. -- #31
 - [x] Any commented-out / dead code anywhere.
 - [x] Legacy Pythonic prototypes of GraphWarpField.
 - [x] ~abstract-away / decomplexify in code shortest-path graph searches and applications~ Moved to #39
